# debe ejecutar el script del examen primero

DROP PROCEDURE IF EXISTS GET_GRUPO;
DROP PROCEDURE IF EXISTS GRUPOS;
DROP PROCEDURE IF EXISTS GET_PARTIDOS;
DROP PROCEDURE IF EXISTS SET_PARTIDO;


DELIMITER $$
CREATE PROCEDURE GET_GRUPO(
	IN _G VARCHAR(1)
)
BEGIN
	SELECT * FROM PAIS_CLASIFICADO WHERE GRUPO = _G;
END$$


CREATE PROCEDURE GRUPOS()
BEGIN
	SELECT DISTINCT GRUPO FROM PAIS_CLASIFICADO ORDER BY GRUPO;
	#SELECT GRUPO FROM PAIS_CLASIFICADO GROUP BY GRUPO;
END$$


CREATE PROCEDURE GET_PARTIDOS(
	IN _A INT,
    IN _B INt
)
BEGIN
	SELECT * FROM PARTIDO_PRIMERA_RONDA WHERE EQUIPO_A = _A AND EQUIPO_B = _B;
    # el sorteo hace que A siempre < B, sino sería algo como:
    # SELECT * FROM PARTIDO_PRIMERA_RONDA WHERE (EQUIPO_A = _A AND EQUIPO_B = _B) OR (EQUIPO_A = _B AND EQUIPO_B = _A);
    # para obtener las combinaciones posibles
END$$


CREATE PROCEDURE SET_PARTIDO(
	IN _A INT,
    IN _B INT,
    IN _GA INT,
    IN _GB INT,
    IN J BOOLEAN
)
BEGIN
	UPDATE PARTIDO_PRIMERA_RONDA
    SET GOLES_EQUIPO_A = _GA,
		GOLES_EQUIPO_B = _GB,
        JUGADO = J
    WHERE EQUIPO_A = _A AND EQUIPO_B = _B;
END$$