delimiter ;
use a20153227;
DROP TABLE IF EXISTS DETALLE_PEDIDO;
DROP TABLE IF EXISTS PEDIDO_FARMACIA;
DROP TABLE IF EXISTS MEDICAMENTO;
DROP TABLE IF EXISTS PACIENTE;
DROP TABLE IF EXISTS PERSONA;
DROP PROCEDURE IF EXISTS REGISTRAR_MEDICAMENTO;
DROP PROCEDURE IF EXISTS REGISTRAR_PACIENTE;
DROP PROCEDURE IF EXISTS LISTAR_PACIENTES;
DROP PROCEDURE IF EXISTS REGISTRAR_PEDIDO;
DROP PROCEDURE IF EXISTS REGISTRAR_DETALLE_PEDIDO;
DROP PROCEDURE IF EXISTS LISTAR_MEDICAMENTOS;

CREATE TABLE PERSONA(
	ID_PERSONA INT PRIMARY KEY AUTO_INCREMENT,
    DNI VARCHAR(8) UNIQUE,
    NOMBRES VARCHAR(50),
    APELLIDO_PATERNO VARCHAR(35),
    SEXO CHAR,
    EDAD INT,
    ESTADO_CIVIL CHAR
);

CREATE TABLE PACIENTE(
	ID_PACIENTE INT PRIMARY KEY,
    APELLIDO_MATERNO VARCHAR(35),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PERSONA (ID_PERSONA)
);

CREATE TABLE MEDICAMENTO(
	ID_MEDICAMENTO INT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(25),
    PRESENTACION VARCHAR(15),
    COSTO_UNIDAD DECIMAL(6,2),
    FARMACEUTICA VARCHAR(25),
    GENERICO_SN BOOL
);

CREATE TABLE PEDIDO_FARMACIA(
	ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    FID_PACIENTE INT,
    FECHA_HORA DATETIME,
    TOTAL DECIMAL(6,2),
    FOREIGN KEY (FID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
);

CREATE TABLE DETALLE_PEDIDO(
	ID_DETALLE_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    FID_PEDIDO INT,
    FID_MEDICAMENTO INT,
    CANTIDAD INT,
    SUBTOTAL DECIMAL(6,2),
    FOREIGN KEY (FID_PEDIDO) REFERENCES PEDIDO_FARMACIA(ID_PEDIDO),
    FOREIGN KEY (FID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO)
);
DELIMITER //
CREATE PROCEDURE REGISTRAR_PACIENTE(
	_DNI VARCHAR(8),
    _NOMBRES VARCHAR(50),
    _APELLIDO_PATERNO VARCHAR(35),
    _APELLIDO_MATERNO VARCHAR(35),
    _SEXO CHAR,
    _EDAD INT,
    _ESTADO_CIVIL CHAR
)
BEGIN
	DECLARE _ID INT;
	INSERT INTO PERSONA (DNI,NOMBRES,APELLIDO_PATERNO,SEXO,EDAD,ESTADO_CIVIL)
    VALUES(_DNI,_NOMBRES,_APELLIDO_PATERNO,_SEXO,_EDAD,_ESTADO_CIVIL);
    SET _ID = last_insert_id();
    INSERT INTO PACIENTE (ID_PACIENTE,APELLIDO_MATERNO) VALUES (_ID,_APELLIDO_MATERNO);
END //
CREATE PROCEDURE REGISTRAR_MEDICAMENTO(
	_NOMBRE VARCHAR(25),
    _PRESENTACION VARCHAR(15),
    _COSTO_UNIDAD DECIMAL(6,2),
    _FARMACEUTICA VARCHAR(25),
    _GENERICO_SN BOOL
)
BEGIN
	INSERT INTO MEDICAMENTO (NOMBRE,PRESENTACION,COSTO_UNIDAD,FARMACEUTICA,GENERICO_SN)
    VALUES (_NOMBRE,_PRESENTACION,_COSTO_UNIDAD,_FARMACEUTICA,_GENERICO_SN);
END //

DELIMITER ;
CALL REGISTRAR_PACIENTE("18720019","JUAN","CHAVEZ","SOLAR",'M',32,'S');
CALL REGISTRAR_PACIENTE("10067291","PEDRO","PEREZ","MARTINEZ",'M',22,'C');
CALL REGISTRAR_PACIENTE("12988102","SOFIA","LEON","TORRES",'F',19,'S');
CALL REGISTRAR_PACIENTE("15321082","ROMINA","NARVAEZ","COSTA",'F',28,'D');
CALL REGISTRAR_PACIENTE("52208251","MAGALY","PAREDES","CASTILLO",'F',23,'S');

CALL REGISTRAR_MEDICAMENTO("PANADOL","500 MG",1.2,"GLAXOSMITHKLINE S.A.",0);
CALL REGISTRAR_MEDICAMENTO("PANADOL","1 G",2.4,"GLAXOSMITHKLINE S.A.",0);
CALL REGISTRAR_MEDICAMENTO("IBUPROFENO","200 MG",1.0,"FARMA PERU",1);
CALL REGISTRAR_MEDICAMENTO("IBUPROFENO","400 MG",1.8,"FARMA PERU",1);
CALL REGISTRAR_MEDICAMENTO("AMOXICILINA","250 MG",0.5,"FARMAINDUSTRIA",1);
CALL REGISTRAR_MEDICAMENTO("AMOXICILINA","500 MG",0.9,"FARMAINDUSTRIA",1);
CALL REGISTRAR_MEDICAMENTO("ALPRAZOLAN","0.5 MG",0.3,"QUALIX",1);
CALL REGISTRAR_MEDICAMENTO("ALPRAZOLAN","1 MG",0.5,"QUALIX",1);
CALL REGISTRAR_MEDICAMENTO("ALPRAZOLAN","2 MG",1.2,"QUALIX",1);
CALL REGISTRAR_MEDICAMENTO("SERTRALIN","20 MG",1.0,"PFIZER",1);
CALL REGISTRAR_MEDICAMENTO("SERTRALIN","50 MG",1.8,"PFIZER",1);
CALL REGISTRAR_MEDICAMENTO("SERTRALIN","100 MG",2.5,"PFIZER",1);
CALL REGISTRAR_MEDICAMENTO("CETIRIZINA","10 MG",1.6,"PHARMACHECK",0);
CALL REGISTRAR_MEDICAMENTO("DIGOXINA","0.25 MG",1.1,"P&SA",0);
CALL REGISTRAR_MEDICAMENTO("DIGOXINA","0.5 MG",2.0,"P&SA",0);
CALL REGISTRAR_MEDICAMENTO("NEUROBION","100 MG",1.4,"MERCK",1);
DELIMITER //
CREATE PROCEDURE LISTAR_PACIENTES()
BEGIN
	SELECT * FROM PERSONA INNER JOIN PACIENTE ON PERSONA.ID_PERSONA = PACIENTE.ID_PACIENTE;
END//
CREATE PROCEDURE LISTAR_MEDICAMENTOS()
BEGIN
	SELECT * FROM MEDICAMENTO;
END//
CREATE PROCEDURE REGISTRAR_PEDIDO(
	_FID_PACIENTE INT,
    _TOTAL DECIMAL(6,2),
	OUT _ID INT
)
BEGIN
	INSERT INTO PEDIDO_FARMACIA(FID_PACIENTE,TOTAL,FECHA_HORA) VALUES(_FID_PACIENTE,_TOTAL,NOW());
	SELECT MAX(ID_PEDIDO) INTO _ID FROM PEDIDO_FARMACIA;
END//
CREATE PROCEDURE REGISTRAR_DETALLE_PEDIDO(
	_FID_PEDIDO INT,
    _FID_MEDICAMENTO INT,
    _CANTIDAD INT,
    _SUBTOTAL DECIMAL(6,2)
)
BEGIN
	INSERT INTO DETALLE_PEDIDO(FID_PEDIDO,FID_MEDICAMENTO,CANTIDAD,SUBTOTAL)
    VALUES (_FID_PEDIDO,_FID_MEDICAMENTO,_CANTIDAD,_SUBTOTAL);
END//