/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package histograma;

import Modelo.Especialidad;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Luiggi Tenorio Ku 20151204
 */
public class Dibujo extends javax.swing.JPanel {

    /**
     * Creates new form Dibujo
     */
    
    
    
    private Color c=Color.BLACK;
    private Especialidad e1=null;
    private Especialidad e2=null;
    
    public Dibujo() {
        initComponents();
    }
    
    public Dibujo(Especialidad id1, Especialidad id2) {
        initComponents();
        e1=id1;
        e2=id2;
        System.out.println("YES");
    }
    
    public Dibujo(Color a) {
        initComponents();
        c=a;
    }

    @Override
    public void paint(Graphics g){
        g.setColor(c);
        g.drawLine(200, 50, 200, 350);
        g.drawLine(100, 300, 700, 300);
        g.drawLine(600, 50, 600, 350);
        //setFocusable(true);
        if(e2!=null){
            int maxcant=e1.getCantidad()+e2.getCantidad();
            g.drawString(e1.getNombre(), 25, 100);
            g.drawString(e2.getNombre(), 25, 200);
            g.drawString(String.valueOf(e1.getCantidad()), 650, 100);
            g.drawString(String.valueOf(e2.getCantidad()), 650, 200);
            //System.out.println((e1.getCantidad()*400.0/maxcant).);
            g.fillRect(200, 100, (int)(e1.getCantidad()*400.0/maxcant), 25);
            g.fillRect(200, 200, (int)(e2.getCantidad()*400.0/maxcant), 25);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
