DROP TABLE IF EXISTS PARTIDO_PRIMERA_RONDA;
DROP TABLE IF EXISTS PAIS_CLASIFICADO;
CREATE TABLE PAIS_CLASIFICADO(
	ID_PAIS_CLASIFICADO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE VARCHAR(25) NOT NULL,
	CATEGORIA_SORTEO INT NOT NULL,
    GRUPO VARCHAR(1) NULL
)Engine=InnoDB;
CREATE TABLE PARTIDO_PRIMERA_RONDA(
	GOLES_EQUIPO_A INT NULL,
    EQUIPO_A INT NOT NULL,
    EQUIPO_B INT NOT NULL,
    GOLES_EQUIPO_B INT,
    JUGADO BOOL NOT NULL,
    PRIMARY KEY (EQUIPO_A,EQUIPO_B),
    FOREIGN KEY (EQUIPO_A) REFERENCES PAIS_CLASIFICADO(ID_PAIS_CLASIFICADO),
    FOREIGN KEY (EQUIPO_B) REFERENCES PAIS_CLASIFICADO(ID_PAIS_CLASIFICADO)
)Engine=InnoDB;
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('RUSIA',1);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('ALEMANIA',1);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('BRASIL',1);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('PORTUGAL',1);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('ARGENTINA',1);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('BELGICA',1);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('POLONIA',1);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('FRANCIA',1);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('ESPAÑA',2);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('PERU',2);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('SUIZA',2);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('INGLATERRA',2);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('COLOMBIA',2);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('MEXICO',2);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('URUGUAY',2);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('CROACIA',2);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('DINAMARCA',3);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('ISLANDIA',3);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('COSTA RICA',3);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('SUECIA',3);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('TUNEZ',3);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('EGIPTO',3);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('SENEGAL',3);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('IRAN',3);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('SERBIA',4);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('NIGERIA',4);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('AUSTRALIA',4);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('JAPON',4);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('MARRUECOS',4);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('PANAMA',4);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('COREA DEL SUR',4);
INSERT INTO PAIS_CLASIFICADO(NOMBRE,CATEGORIA_SORTEO) VALUES('ARABIA SAUDI',4);
DROP PROCEDURE IF EXISTS REALIZAR_SORTEO;
DELIMITER $
CREATE PROCEDURE REALIZAR_SORTEO()
BEGIN
	declare bNoMoreRows boolean DEFAULT FALSE;
	DECLARE AG CURSOR FOR SELECT ID_PAIS_CLASIFICADO FROM TABLA_TEMPORAL;
    declare continue handler for not found set bNoMoreRows = true; 
BEGIN
	DECLARE NUMERO INTEGER;
	DECLARE i INTEGER;
    DECLARE j INTEGER;
    DECLARE z INTEGER;
    DECLARE anfitrion BOOL DEFAULT TRUE;
    DECLARE _grupo VARCHAR(1);
    DECLARE aleatorio INTEGER;
    DECLARE _ID_PAIS_CLASIFICADO INTEGER;
	SET i = 1;
    grupos_loop: LOOP
		DROP TEMPORARY TABLE IF EXISTS TABLA_TEMPORAL;
		CREATE TEMPORARY TABLE TABLA_TEMPORAL (ID_PAIS_CLASIFICADO INT PRIMARY KEY, NOMBRE VARCHAR(25)) engine=memory as (
		SELECT ID_PAIS_CLASIFICADO, NOMBRE FROM PAIS_CLASIFICADO WHERE CATEGORIA_SORTEO = i);
        SET z=1;
            grupo_esp: LOOP
			SELECT count(*) into NUMERO FROM TABLA_TEMPORAL;
			SET aleatorio = CAST((RAND() * (NUMERO-1))+1 AS UNSIGNED);
			OPEN AG;
			SET j = 1;
            SET bNoMoreRows = false;
				read_loop: LOOP
					FETCH AG INTO _ID_PAIS_CLASIFICADO;
                    IF (j = aleatorio) then
						IF (z=1) then
							SET _grupo = 'A';
						end if;
						if (z=2) then
							SET _grupo = 'B';
                        end if;
                        if (z=3) then
							SET _grupo = 'C';
                        end if;
                        if (z=4) then
							SET _grupo = 'D';
                        end if;
                        if (z=5) then
							SET _grupo = 'E';
                        end if;
                        if (z=6) then
							SET _grupo = 'F';
                        end if;
                        if (z=7) then
							SET _grupo = 'G';
                        end if;
                        if (z=8) then
							SET _grupo = 'H';
                        end if;
                        IF anfitrion THEN
							SELECT ID_PAIS_CLASIFICADO INTO _ID_PAIS_CLASIFICADO FROM PAIS_CLASIFICADO WHERE NOMBRE = 'RUSIA';
                            SET anfitrion = false;
                        END IF;
						UPDATE PAIS_CLASIFICADO SET GRUPO = _grupo WHERE ID_PAIS_CLASIFICADO = _ID_PAIS_CLASIFICADO;
						DELETE FROM TABLA_TEMPORAL WHERE ID_PAIS_CLASIFICADO = _ID_PAIS_CLASIFICADO;
						SET bNoMoreRows = TRUE;
					END IF;
					IF bNoMoreRows then
						LEAVE read_loop;
					end if;
					SET j = j + 1;
				END LOOP read_loop;
                CLOSE AG;
				IF (z = 8) THEN
					LEAVE grupo_esp;
                END IF;
                SET z = 1 + z;
			END LOOP grupo_esp;
        IF (i = 4) then
			DROP TEMPORARY TABLE IF EXISTS TABLA_TEMPORAL;
			LEAVE grupos_loop;
        end if;
        SET i = i + 1;
	END LOOP grupos_loop;
END;
END$
CALL REALIZAR_SORTEO()$
DROP PROCEDURE IF EXISTS CREAR_PARTIDOS$
CREATE PROCEDURE CREAR_PARTIDOS()
BEGIN
	DECLARE bNoMoreRows boolean DEFAULT FALSE;
    DECLARE AG CURSOR FOR SELECT ID_PAIS_CLASIFICADO FROM TABLA_TEMPORAL;
    declare continue handler for not found set bNoMoreRows = true; 
BEGIN
	DECLARE i INTEGER;
    DECLARE j INTEGER;
    DECLARE LETRA_GRUPO VARCHAR(1);
    DECLARE _equipoA INTEGER;
	DECLARE _equipoB INTEGER;
    SET i = 1;
    grupos_loop: LOOP
		IF i = 1 then
			SET LETRA_GRUPO = 'A';
        END IF;
        IF i = 2 then
			SET LETRA_GRUPO = 'B';
        END IF;
        IF i = 3 then
			SET LETRA_GRUPO = 'C';
        END IF;
        IF i = 4 then
			SET LETRA_GRUPO = 'D';
        END IF;
        IF i = 5 then
			SET LETRA_GRUPO = 'E';
        END IF;
        IF i = 6 then
			SET LETRA_GRUPO = 'F';
        END IF;
        IF i = 7 then
			SET LETRA_GRUPO = 'G';
        END IF;
        IF i = 8 then
			SET LETRA_GRUPO = 'H';
        END IF;
		DROP TEMPORARY TABLE IF EXISTS TABLA_TEMPORAL;
		CREATE TEMPORARY TABLE TABLA_TEMPORAL(ID_PAIS_CLASIFICADO INT PRIMARY KEY) AS
        SELECT ID_PAIS_CLASIFICADO FROM PAIS_CLASIFICADO WHERE GRUPO = LETRA_GRUPO;
        partidos_loop: LOOP
			OPEN AG;
            FETCH AG into _equipoA;
            IF bNoMoreRows THEN
					CLOSE AG;
					LEAVE partidos_loop;
            END IF;
            DELETE FROM TABLA_TEMPORAL WHERE ID_PAIS_CLASIFICADO = _equipoA;
            CLOSE AG;
            OPEN AG;
            contrincantes: LOOP
				FETCH AG into _equipoB;
                IF bNoMoreRows THEN
					CLOSE AG;
					LEAVE contrincantes;
                END IF;
                INSERT INTO PARTIDO_PRIMERA_RONDA(EQUIPO_A,EQUIPO_B,JUGADO) VALUES(_equipoA,_equipoB,false);
            END LOOP contrincantes;
            SET bNoMoreRows = false;
        END LOOP partidos_loop;
        SET bNoMoreRows = false;
        IF i = 8 then
			DROP TEMPORARY TABLE IF EXISTS TABLA_TEMPORAL;
			LEAVE grupos_loop;
        END IF;
        SET i = i + 1;
    END LOOP grupos_loop;
END;    
END$
CALL CREAR_PARTIDOS()$