//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control.ProyWebServ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Service/", ConfigurationName="ProyWebServ.exWService")]
    public interface exWService {
        
        // CODEGEN: Parameter 'a' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/exWService/updtPartidoRequest", ReplyAction="http://Service/exWService/updtPartidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Control.ProyWebServ.updtPartidoResponse updtPartido(Control.ProyWebServ.updtPartidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/exWService/updtPartidoRequest", ReplyAction="http://Service/exWService/updtPartidoResponse")]
        System.Threading.Tasks.Task<Control.ProyWebServ.updtPartidoResponse> updtPartidoAsync(Control.ProyWebServ.updtPartidoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/exWService/helloRequest", ReplyAction="http://Service/exWService/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Control.ProyWebServ.helloResponse hello(Control.ProyWebServ.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/exWService/helloRequest", ReplyAction="http://Service/exWService/helloResponse")]
        System.Threading.Tasks.Task<Control.ProyWebServ.helloResponse> helloAsync(Control.ProyWebServ.helloRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/exWService/getPartidosRequest", ReplyAction="http://Service/exWService/getPartidosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Control.ProyWebServ.getPartidosResponse getPartidos(Control.ProyWebServ.getPartidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/exWService/getPartidosRequest", ReplyAction="http://Service/exWService/getPartidosResponse")]
        System.Threading.Tasks.Task<Control.ProyWebServ.getPartidosResponse> getPartidosAsync(Control.ProyWebServ.getPartidosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/exWService/getGruposRequest", ReplyAction="http://Service/exWService/getGruposResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Control.ProyWebServ.getGruposResponse getGrupos(Control.ProyWebServ.getGruposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/exWService/getGruposRequest", ReplyAction="http://Service/exWService/getGruposResponse")]
        System.Threading.Tasks.Task<Control.ProyWebServ.getGruposResponse> getGruposAsync(Control.ProyWebServ.getGruposRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/exWService/getPaisesRequest", ReplyAction="http://Service/exWService/getPaisesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Control.ProyWebServ.getPaisesResponse getPaises(Control.ProyWebServ.getPaisesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/exWService/getPaisesRequest", ReplyAction="http://Service/exWService/getPaisesResponse")]
        System.Threading.Tasks.Task<Control.ProyWebServ.getPaisesResponse> getPaisesAsync(Control.ProyWebServ.getPaisesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updtPartido", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class updtPartidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int b;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ga;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int gb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool jug;
        
        public updtPartidoRequest() {
        }
        
        public updtPartidoRequest(int a, int b, int ga, int gb, bool jug) {
            this.a = a;
            this.b = b;
            this.ga = ga;
            this.gb = gb;
            this.jug = jug;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updtPartidoResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class updtPartidoResponse {
        
        public updtPartidoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Service/")]
    public partial class partido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int eqAField;
        
        private int eqBField;
        
        private bool jugadoField;
        
        private int gEqAField;
        
        private int gEqBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int eqA {
            get {
                return this.eqAField;
            }
            set {
                this.eqAField = value;
                this.RaisePropertyChanged("eqA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int eqB {
            get {
                return this.eqBField;
            }
            set {
                this.eqBField = value;
                this.RaisePropertyChanged("eqB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool jugado {
            get {
                return this.jugadoField;
            }
            set {
                this.jugadoField = value;
                this.RaisePropertyChanged("jugado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int gEqA {
            get {
                return this.gEqAField;
            }
            set {
                this.gEqAField = value;
                this.RaisePropertyChanged("gEqA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int gEqB {
            get {
                return this.gEqBField;
            }
            set {
                this.gEqBField = value;
                this.RaisePropertyChanged("gEqB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Service/")]
    public partial class pais : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int catField;
        
        private int dfField;
        
        private int gcField;
        
        private int gfField;
        
        private ushort grpField;
        
        private int idField;
        
        private string nombreField;
        
        private int peField;
        
        private int pgField;
        
        private int pjField;
        
        private int ppField;
        
        private int ptsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cat {
            get {
                return this.catField;
            }
            set {
                this.catField = value;
                this.RaisePropertyChanged("cat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int df {
            get {
                return this.dfField;
            }
            set {
                this.dfField = value;
                this.RaisePropertyChanged("df");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int gc {
            get {
                return this.gcField;
            }
            set {
                this.gcField = value;
                this.RaisePropertyChanged("gc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int gf {
            get {
                return this.gfField;
            }
            set {
                this.gfField = value;
                this.RaisePropertyChanged("gf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ushort grp {
            get {
                return this.grpField;
            }
            set {
                this.grpField = value;
                this.RaisePropertyChanged("grp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int pe {
            get {
                return this.peField;
            }
            set {
                this.peField = value;
                this.RaisePropertyChanged("pe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int pg {
            get {
                return this.pgField;
            }
            set {
                this.pgField = value;
                this.RaisePropertyChanged("pg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int pj {
            get {
                return this.pjField;
            }
            set {
                this.pjField = value;
                this.RaisePropertyChanged("pj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int pp {
            get {
                return this.ppField;
            }
            set {
                this.ppField = value;
                this.RaisePropertyChanged("pp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int pts {
            get {
                return this.ptsField;
            }
            set {
                this.ptsField = value;
                this.RaisePropertyChanged("pts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPartidos", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class getPartidosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("pares", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] pares;
        
        public getPartidosRequest() {
        }
        
        public getPartidosRequest(int[] pares) {
            this.pares = pares;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPartidosResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class getPartidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Control.ProyWebServ.partido[] @return;
        
        public getPartidosResponse() {
        }
        
        public getPartidosResponse(Control.ProyWebServ.partido[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGrupos", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class getGruposRequest {
        
        public getGruposRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getGruposResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class getGruposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getGruposResponse() {
        }
        
        public getGruposResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPaises", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class getPaisesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string grupo;
        
        public getPaisesRequest() {
        }
        
        public getPaisesRequest(string grupo) {
            this.grupo = grupo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPaisesResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class getPaisesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Control.ProyWebServ.pais[] @return;
        
        public getPaisesResponse() {
        }
        
        public getPaisesResponse(Control.ProyWebServ.pais[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface exWServiceChannel : Control.ProyWebServ.exWService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class exWServiceClient : System.ServiceModel.ClientBase<Control.ProyWebServ.exWService>, Control.ProyWebServ.exWService {
        
        public exWServiceClient() {
        }
        
        public exWServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public exWServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public exWServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public exWServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Control.ProyWebServ.updtPartidoResponse Control.ProyWebServ.exWService.updtPartido(Control.ProyWebServ.updtPartidoRequest request) {
            return base.Channel.updtPartido(request);
        }
        
        public void updtPartido(int a, int b, int ga, int gb, bool jug) {
            Control.ProyWebServ.updtPartidoRequest inValue = new Control.ProyWebServ.updtPartidoRequest();
            inValue.a = a;
            inValue.b = b;
            inValue.ga = ga;
            inValue.gb = gb;
            inValue.jug = jug;
            Control.ProyWebServ.updtPartidoResponse retVal = ((Control.ProyWebServ.exWService)(this)).updtPartido(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Control.ProyWebServ.updtPartidoResponse> Control.ProyWebServ.exWService.updtPartidoAsync(Control.ProyWebServ.updtPartidoRequest request) {
            return base.Channel.updtPartidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Control.ProyWebServ.updtPartidoResponse> updtPartidoAsync(int a, int b, int ga, int gb, bool jug) {
            Control.ProyWebServ.updtPartidoRequest inValue = new Control.ProyWebServ.updtPartidoRequest();
            inValue.a = a;
            inValue.b = b;
            inValue.ga = ga;
            inValue.gb = gb;
            inValue.jug = jug;
            return ((Control.ProyWebServ.exWService)(this)).updtPartidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Control.ProyWebServ.helloResponse Control.ProyWebServ.exWService.hello(Control.ProyWebServ.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            Control.ProyWebServ.helloRequest inValue = new Control.ProyWebServ.helloRequest();
            inValue.name = name;
            Control.ProyWebServ.helloResponse retVal = ((Control.ProyWebServ.exWService)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Control.ProyWebServ.helloResponse> Control.ProyWebServ.exWService.helloAsync(Control.ProyWebServ.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Control.ProyWebServ.helloResponse> helloAsync(string name) {
            Control.ProyWebServ.helloRequest inValue = new Control.ProyWebServ.helloRequest();
            inValue.name = name;
            return ((Control.ProyWebServ.exWService)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Control.ProyWebServ.getPartidosResponse Control.ProyWebServ.exWService.getPartidos(Control.ProyWebServ.getPartidosRequest request) {
            return base.Channel.getPartidos(request);
        }
        
        public Control.ProyWebServ.partido[] getPartidos(int[] pares) {
            Control.ProyWebServ.getPartidosRequest inValue = new Control.ProyWebServ.getPartidosRequest();
            inValue.pares = pares;
            Control.ProyWebServ.getPartidosResponse retVal = ((Control.ProyWebServ.exWService)(this)).getPartidos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Control.ProyWebServ.getPartidosResponse> Control.ProyWebServ.exWService.getPartidosAsync(Control.ProyWebServ.getPartidosRequest request) {
            return base.Channel.getPartidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Control.ProyWebServ.getPartidosResponse> getPartidosAsync(int[] pares) {
            Control.ProyWebServ.getPartidosRequest inValue = new Control.ProyWebServ.getPartidosRequest();
            inValue.pares = pares;
            return ((Control.ProyWebServ.exWService)(this)).getPartidosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Control.ProyWebServ.getGruposResponse Control.ProyWebServ.exWService.getGrupos(Control.ProyWebServ.getGruposRequest request) {
            return base.Channel.getGrupos(request);
        }
        
        public string[] getGrupos() {
            Control.ProyWebServ.getGruposRequest inValue = new Control.ProyWebServ.getGruposRequest();
            Control.ProyWebServ.getGruposResponse retVal = ((Control.ProyWebServ.exWService)(this)).getGrupos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Control.ProyWebServ.getGruposResponse> Control.ProyWebServ.exWService.getGruposAsync(Control.ProyWebServ.getGruposRequest request) {
            return base.Channel.getGruposAsync(request);
        }
        
        public System.Threading.Tasks.Task<Control.ProyWebServ.getGruposResponse> getGruposAsync() {
            Control.ProyWebServ.getGruposRequest inValue = new Control.ProyWebServ.getGruposRequest();
            return ((Control.ProyWebServ.exWService)(this)).getGruposAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Control.ProyWebServ.getPaisesResponse Control.ProyWebServ.exWService.getPaises(Control.ProyWebServ.getPaisesRequest request) {
            return base.Channel.getPaises(request);
        }
        
        public Control.ProyWebServ.pais[] getPaises(string grupo) {
            Control.ProyWebServ.getPaisesRequest inValue = new Control.ProyWebServ.getPaisesRequest();
            inValue.grupo = grupo;
            Control.ProyWebServ.getPaisesResponse retVal = ((Control.ProyWebServ.exWService)(this)).getPaises(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Control.ProyWebServ.getPaisesResponse> Control.ProyWebServ.exWService.getPaisesAsync(Control.ProyWebServ.getPaisesRequest request) {
            return base.Channel.getPaisesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Control.ProyWebServ.getPaisesResponse> getPaisesAsync(string grupo) {
            Control.ProyWebServ.getPaisesRequest inValue = new Control.ProyWebServ.getPaisesRequest();
            inValue.grupo = grupo;
            return ((Control.ProyWebServ.exWService)(this)).getPaisesAsync(inValue);
        }
    }
}
