//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaNegocio.AeropuertoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aeropuerto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Aeropuerto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        private int Mts_alturaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }

        public object id { get; internal set; }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Mts_altura {
            get {
                return this.Mts_alturaField;
            }
            set {
                if ((this.Mts_alturaField.Equals(value) != true)) {
                    this.Mts_alturaField = value;
                    this.RaisePropertyChanged("Mts_altura");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AeropuertoWS.AeropuertoWSSoap")]
    public interface AeropuertoWSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        LogicaNegocio.AeropuertoWS.HelloWorldResponse HelloWorld(LogicaNegocio.AeropuertoWS.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<LogicaNegocio.AeropuertoWS.HelloWorldResponse> HelloWorldAsync(LogicaNegocio.AeropuertoWS.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento a del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar", ReplyAction="*")]
        LogicaNegocio.AeropuertoWS.registrarResponse registrar(LogicaNegocio.AeropuertoWS.registrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar", ReplyAction="*")]
        System.Threading.Tasks.Task<LogicaNegocio.AeropuertoWS.registrarResponse> registrarAsync(LogicaNegocio.AeropuertoWS.registrarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listar", ReplyAction="*")]
        LogicaNegocio.AeropuertoWS.listarResponse listar(LogicaNegocio.AeropuertoWS.listarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listar", ReplyAction="*")]
        System.Threading.Tasks.Task<LogicaNegocio.AeropuertoWS.listarResponse> listarAsync(LogicaNegocio.AeropuertoWS.listarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar", ReplyAction="*")]
        void eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task eliminarAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento a del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificar", ReplyAction="*")]
        LogicaNegocio.AeropuertoWS.modificarResponse modificar(LogicaNegocio.AeropuertoWS.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificar", ReplyAction="*")]
        System.Threading.Tasks.Task<LogicaNegocio.AeropuertoWS.modificarResponse> modificarAsync(LogicaNegocio.AeropuertoWS.modificarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public LogicaNegocio.AeropuertoWS.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(LogicaNegocio.AeropuertoWS.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public LogicaNegocio.AeropuertoWS.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(LogicaNegocio.AeropuertoWS.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrar", Namespace="http://tempuri.org/", Order=0)]
        public LogicaNegocio.AeropuertoWS.registrarRequestBody Body;
        
        public registrarRequest() {
        }
        
        public registrarRequest(LogicaNegocio.AeropuertoWS.registrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LogicaNegocio.AeropuertoWS.Aeropuerto a;
        
        public registrarRequestBody() {
        }
        
        public registrarRequestBody(LogicaNegocio.AeropuertoWS.Aeropuerto a) {
            this.a = a;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarResponse", Namespace="http://tempuri.org/", Order=0)]
        public LogicaNegocio.AeropuertoWS.registrarResponseBody Body;
        
        public registrarResponse() {
        }
        
        public registrarResponse(LogicaNegocio.AeropuertoWS.registrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int registrarResult;
        
        public registrarResponseBody() {
        }
        
        public registrarResponseBody(int registrarResult) {
            this.registrarResult = registrarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listar", Namespace="http://tempuri.org/", Order=0)]
        public LogicaNegocio.AeropuertoWS.listarRequestBody Body;
        
        public listarRequest() {
        }
        
        public listarRequest(LogicaNegocio.AeropuertoWS.listarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarRequestBody {
        
        public listarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarResponse", Namespace="http://tempuri.org/", Order=0)]
        public LogicaNegocio.AeropuertoWS.listarResponseBody Body;
        
        public listarResponse() {
        }
        
        public listarResponse(LogicaNegocio.AeropuertoWS.listarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LogicaNegocio.AeropuertoWS.Aeropuerto[] listarResult;
        
        public listarResponseBody() {
        }
        
        public listarResponseBody(LogicaNegocio.AeropuertoWS.Aeropuerto[] listarResult) {
            this.listarResult = listarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificar", Namespace="http://tempuri.org/", Order=0)]
        public LogicaNegocio.AeropuertoWS.modificarRequestBody Body;
        
        public modificarRequest() {
        }
        
        public modificarRequest(LogicaNegocio.AeropuertoWS.modificarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LogicaNegocio.AeropuertoWS.Aeropuerto a;
        
        public modificarRequestBody() {
        }
        
        public modificarRequestBody(LogicaNegocio.AeropuertoWS.Aeropuerto a) {
            this.a = a;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarResponse", Namespace="http://tempuri.org/", Order=0)]
        public LogicaNegocio.AeropuertoWS.modificarResponseBody Body;
        
        public modificarResponse() {
        }
        
        public modificarResponse(LogicaNegocio.AeropuertoWS.modificarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class modificarResponseBody {
        
        public modificarResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AeropuertoWSSoapChannel : LogicaNegocio.AeropuertoWS.AeropuertoWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AeropuertoWSSoapClient : System.ServiceModel.ClientBase<LogicaNegocio.AeropuertoWS.AeropuertoWSSoap>, LogicaNegocio.AeropuertoWS.AeropuertoWSSoap {
        
        public AeropuertoWSSoapClient() {
        }
        
        public AeropuertoWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AeropuertoWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AeropuertoWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AeropuertoWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicaNegocio.AeropuertoWS.HelloWorldResponse LogicaNegocio.AeropuertoWS.AeropuertoWSSoap.HelloWorld(LogicaNegocio.AeropuertoWS.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            LogicaNegocio.AeropuertoWS.HelloWorldRequest inValue = new LogicaNegocio.AeropuertoWS.HelloWorldRequest();
            inValue.Body = new LogicaNegocio.AeropuertoWS.HelloWorldRequestBody();
            LogicaNegocio.AeropuertoWS.HelloWorldResponse retVal = ((LogicaNegocio.AeropuertoWS.AeropuertoWSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogicaNegocio.AeropuertoWS.HelloWorldResponse> LogicaNegocio.AeropuertoWS.AeropuertoWSSoap.HelloWorldAsync(LogicaNegocio.AeropuertoWS.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogicaNegocio.AeropuertoWS.HelloWorldResponse> HelloWorldAsync() {
            LogicaNegocio.AeropuertoWS.HelloWorldRequest inValue = new LogicaNegocio.AeropuertoWS.HelloWorldRequest();
            inValue.Body = new LogicaNegocio.AeropuertoWS.HelloWorldRequestBody();
            return ((LogicaNegocio.AeropuertoWS.AeropuertoWSSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicaNegocio.AeropuertoWS.registrarResponse LogicaNegocio.AeropuertoWS.AeropuertoWSSoap.registrar(LogicaNegocio.AeropuertoWS.registrarRequest request) {
            return base.Channel.registrar(request);
        }
        
        public int registrar(LogicaNegocio.AeropuertoWS.Aeropuerto a) {
            LogicaNegocio.AeropuertoWS.registrarRequest inValue = new LogicaNegocio.AeropuertoWS.registrarRequest();
            inValue.Body = new LogicaNegocio.AeropuertoWS.registrarRequestBody();
            inValue.Body.a = a;
            LogicaNegocio.AeropuertoWS.registrarResponse retVal = ((LogicaNegocio.AeropuertoWS.AeropuertoWSSoap)(this)).registrar(inValue);
            return retVal.Body.registrarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogicaNegocio.AeropuertoWS.registrarResponse> LogicaNegocio.AeropuertoWS.AeropuertoWSSoap.registrarAsync(LogicaNegocio.AeropuertoWS.registrarRequest request) {
            return base.Channel.registrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogicaNegocio.AeropuertoWS.registrarResponse> registrarAsync(LogicaNegocio.AeropuertoWS.Aeropuerto a) {
            LogicaNegocio.AeropuertoWS.registrarRequest inValue = new LogicaNegocio.AeropuertoWS.registrarRequest();
            inValue.Body = new LogicaNegocio.AeropuertoWS.registrarRequestBody();
            inValue.Body.a = a;
            return ((LogicaNegocio.AeropuertoWS.AeropuertoWSSoap)(this)).registrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicaNegocio.AeropuertoWS.listarResponse LogicaNegocio.AeropuertoWS.AeropuertoWSSoap.listar(LogicaNegocio.AeropuertoWS.listarRequest request) {
            return base.Channel.listar(request);
        }
        
        public LogicaNegocio.AeropuertoWS.Aeropuerto[] listar() {
            LogicaNegocio.AeropuertoWS.listarRequest inValue = new LogicaNegocio.AeropuertoWS.listarRequest();
            inValue.Body = new LogicaNegocio.AeropuertoWS.listarRequestBody();
            LogicaNegocio.AeropuertoWS.listarResponse retVal = ((LogicaNegocio.AeropuertoWS.AeropuertoWSSoap)(this)).listar(inValue);
            return retVal.Body.listarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogicaNegocio.AeropuertoWS.listarResponse> LogicaNegocio.AeropuertoWS.AeropuertoWSSoap.listarAsync(LogicaNegocio.AeropuertoWS.listarRequest request) {
            return base.Channel.listarAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogicaNegocio.AeropuertoWS.listarResponse> listarAsync() {
            LogicaNegocio.AeropuertoWS.listarRequest inValue = new LogicaNegocio.AeropuertoWS.listarRequest();
            inValue.Body = new LogicaNegocio.AeropuertoWS.listarRequestBody();
            return ((LogicaNegocio.AeropuertoWS.AeropuertoWSSoap)(this)).listarAsync(inValue);
        }
        
        public void eliminar(int id) {
            base.Channel.eliminar(id);
        }
        
        public System.Threading.Tasks.Task eliminarAsync(int id) {
            return base.Channel.eliminarAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogicaNegocio.AeropuertoWS.modificarResponse LogicaNegocio.AeropuertoWS.AeropuertoWSSoap.modificar(LogicaNegocio.AeropuertoWS.modificarRequest request) {
            return base.Channel.modificar(request);
        }
        
        public void modificar(LogicaNegocio.AeropuertoWS.Aeropuerto a) {
            LogicaNegocio.AeropuertoWS.modificarRequest inValue = new LogicaNegocio.AeropuertoWS.modificarRequest();
            inValue.Body = new LogicaNegocio.AeropuertoWS.modificarRequestBody();
            inValue.Body.a = a;
            LogicaNegocio.AeropuertoWS.modificarResponse retVal = ((LogicaNegocio.AeropuertoWS.AeropuertoWSSoap)(this)).modificar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogicaNegocio.AeropuertoWS.modificarResponse> LogicaNegocio.AeropuertoWS.AeropuertoWSSoap.modificarAsync(LogicaNegocio.AeropuertoWS.modificarRequest request) {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogicaNegocio.AeropuertoWS.modificarResponse> modificarAsync(LogicaNegocio.AeropuertoWS.Aeropuerto a) {
            LogicaNegocio.AeropuertoWS.modificarRequest inValue = new LogicaNegocio.AeropuertoWS.modificarRequest();
            inValue.Body = new LogicaNegocio.AeropuertoWS.modificarRequestBody();
            inValue.Body.a = a;
            return ((LogicaNegocio.AeropuertoWS.AeropuertoWSSoap)(this)).modificarAsync(inValue);
        }
    }
}
