package productor.consumidor;

import java.util.concurrent.Semaphore;
import javax.swing.DefaultListModel;

public class formulario extends javax.swing.JFrame {
  
    /*Semáforo para sección crítica de los consumidores:
    Evitar que dos o más consumidores accedan al mismo elemento*/
    public static Semaphore mutex;
    
    /*Semáforo para evitar que se consuma cuando el buffer está vacío*/
    public static Semaphore sem;
    
    /*Semáforo para evitar que se produzca cuando el buffer está lleno*/
    public static Semaphore buffer;
    
    static final int SIZE_BUFFER = 3;
    
    /* Modelos de trabajo*/
    public static DefaultListModel modeloProductor;
    public static DefaultListModel modeloConsumidor1;
    public static DefaultListModel modeloConsumidor2;
    
    public formulario() {
        initComponents();
        this.setResizable(false);
        
        // Inicializando semáforos
        mutex = new Semaphore(1);
        buffer = new Semaphore(SIZE_BUFFER);
        sem = new Semaphore(0);
        
        // Inicializando modelos de trabajo
        modeloProductor = new DefaultListModel();
        modeloConsumidor1 = new DefaultListModel();
        modeloConsumidor2 = new DefaultListModel();
        
        // Asociando el modelo a las listas
        listProductor.setModel(modeloProductor);
        listConsumidor1.setModel(modeloConsumidor1);
        listConsumidor2.setModel(modeloConsumidor2);
        
        //Creando un Productor
        productor P = new productor();
        //Iniciar Productor
        P.start();
        
        //Creando dos Consumidores
        consumidor C1 = new consumidor(modeloConsumidor1);
        consumidor C2 = new consumidor(modeloConsumidor2);
        //Iniciar Consumidores
        C1.start();
        C2.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspProductor = new javax.swing.JScrollPane();
        listProductor = new javax.swing.JList();
        lblProductor = new javax.swing.JLabel();
        jspConsumidor1 = new javax.swing.JScrollPane();
        listConsumidor1 = new javax.swing.JList();
        jspConsumidor2 = new javax.swing.JScrollPane();
        listConsumidor2 = new javax.swing.JList();
        lblConsumidor1 = new javax.swing.JLabel();
        lblConsumidor2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listProductor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listProductor.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jspProductor.setViewportView(listProductor);

        lblProductor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProductor.setText("Productor:");

        listConsumidor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listConsumidor1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jspConsumidor1.setViewportView(listConsumidor1);

        listConsumidor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        listConsumidor2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jspConsumidor2.setViewportView(listConsumidor2);

        lblConsumidor1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblConsumidor1.setText("Consumidor 1:");

        lblConsumidor2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblConsumidor2.setText("Consumidor 2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProductor)
                    .addComponent(jspProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspConsumidor2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsumidor1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConsumidor2)
                    .addComponent(jspConsumidor1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsumidor1)
                    .addComponent(lblProductor)
                    .addComponent(lblConsumidor2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspConsumidor2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspConsumidor1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jspConsumidor1;
    private javax.swing.JScrollPane jspConsumidor2;
    private javax.swing.JScrollPane jspProductor;
    private javax.swing.JLabel lblConsumidor1;
    private javax.swing.JLabel lblConsumidor2;
    private javax.swing.JLabel lblProductor;
    private javax.swing.JList listConsumidor1;
    private javax.swing.JList listConsumidor2;
    private javax.swing.JList listProductor;
    // End of variables declaration//GEN-END:variables
}
